### ISSUE TITLE
This TODO checker is a bit intrusive: it got into my git hooks when installed

### ISSUE THREAD

**Issue by gl-yziquel** [SimonStJG/flake8-jira-todo-checker#8]
Hi.

I installed the `flake8-jira-todo-checker`plugin from source, with `pip install . --user`. I find this flake8 plugin a bit intrusive: as soon as it was installed, it automatically got picked up by `flake8`, and it is now running in my pre-push git hooks automatically. Which prevents me from pushing.

I'd appreciate a somewhat less intrusive approach: get it configured to enable it before getting that plugin picked by just whatever git hook happens to be running.

Is this how flake8 plugins are supposed to be run ? You install them, and just by that, they run automatically ?

If yes, this issue is irrelevant. If no, then I'd argue in favour of making flake8-jira-todo-checker less intrusive. Because, as of now, I have to uninstall it to get back to a productive workflow. Which is a shame. As I'd really like to have it handy.

And, please: make it a bit easier to understand how it is to be configured. I don't see configuration snippets in the README, and I'll therefore have to investigate more than I'd need to to get your plugin up and running.

**Comment by SimonStJG** [comment]
Hello,

Regarding automatically running I'm afraid that's flake8's behaviour, not this plugin, see https://flake8.pycqa.org/en/6.1.0/user/using-plugins.html 

> After installation, most plugins immediately start reporting errors

It's not my favourite behaviour either!  You could suppress the errors from the plugin in your git hook though if you don't want them, e.g. using --extend-ignore.

All the config options can be passed in the usual ways for a flake8 plugin, there's some examples in the tests https://github.com/SimonStJG/flake8-jira-todo-checker/blob/ab9eb52686aa91aa423910079ab8012447d4bfbe/test/test_flake8_jira_todo_checker.py#L201  

Happy to accept docs PRs if you think they could be clearer.

**Comment by gl-yziquel** [comment]
Thank you for the clarification.
